#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication reconstructPar
runApplication postProcess -func sample -noZero
cd plot
python3 plot.py

#------------------------------------------------------------------------------

