#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication chemkinToFoam \
               chemkin/chem.inp chemkin/therm.dat chemkin/transportProperties \
               constant/reactions constant/thermo
               
cp -r 0.orig/ 0/
runApplication blockMesh
runApplication setFields
runApplication decomposePar

#------------------------------------------------------------------------------
