#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

paraFoam -builtin -touch

./Allpre
runParallel $(getApplication)
./Allpost

#------------------------------------------------------------------------------
