#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

paraFoam -builtin -touch

runApplication blockMesh

runApplication decomposePar

runParallel foamRun

runApplication reconstructPar -time '0.2, 0.4, 3'

runApplication -s sampleAlongLine foamPostProcess -time '0.2, 0.4, 3' -func sampleAlongLine

#------------------------------------------------------------------------------
