#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

paraFoam -builtin -touch

runApplication setFields

## Parallel
runApplication decomposePar

runParallel foamRun

runApplication reconstructPar -latestTime

runApplication -s mySampling foamPostProcess -latestTime -func mySampleDict

#------------------------------------------------------------------------------
