#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

paraFoam -builtin -touch

runApplication blockMesh

runApplication createPatch

runApplication setFields

runApplication foamRun

# ----------------------------------------------------------------- end-of-file
